apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deploy.name }}
  labels:
    app: {{ .Values.frontend.labels.app }}
spec:
  replicas: {{ .Values.frontend.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.labels.app }}
    spec:
      containers:
        - name: {{ .Values.frontend.deploy.containers.name }}
          imagePullPolicy: {{ .Values.frontend.deploy.containers.imagePullPolicy }}
          image: "{{ .Values.frontend.deploy.containers.image }}:{{ .Values.frontend.deploy.containers.tag }}"
          ports:
            - containerPort: 80 
              name: http 

      imagePullSecrets:
      - name: postgres-secret
      - name: redis-secret
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # select the users pod and expose
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80