apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_HOST: "postgres-postgresql.postgres.svc.cluster.local"
  REDIS_HOST: "redis-master.redis.svc.cluster.local:6379"