apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.AppName }}
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.AppsPorts.http.port}}
      targetPort: {{.Values.AppsPorts.http.targetPort}}
    - name: https
      protocol: TCP
      port: {{.Values.AppsPorts.https.port}}
      targetPort: {{.Values.AppsPorts.https.targetPort}}

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  {{if eq .Values.tls true}}
     cert-manager.io/cluster-issuer: letsencrypt-prod
  {{end}}

spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: error
      port:
        name: svc-port
{{if eq .Values.tls true}}
  tls:
  - hosts: 
    - host1.domain.ext
    - host2.domain.ext
    secretName: {{ .Release.Name }}-tls
{{end}}
  rules:
  - host: 
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-service
              port:
                number: {{.Values.AppsPorts.http.port}}

--- 

apiVersion: networking.k8s.io/v1
# For versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress  # Replace with your desired name
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Replace if using a different controller
    # Optional: Annotations for TLS configuration if desired
spec:
  rules:
    - host: your-domain.com  # Replace with your domain name
      http:
        paths:
          - path: /  # Route root path to your frontend
            pathType: Prefix
            backend:
              service:
                name: my-frontend-svc  # Replace with your frontend service name
                port:
                  number: 80  # Or the port your frontend service listens on
          - path: /api(/|$)(.*)  # Route API paths to your backend
            pathType: Prefix
            backend:
              service:
                name: my-backend-svc  # Replace with your backend service name
                port:
                  number: 8080  # Or the port your backend service listens on
