version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  azure-aks: circleci/azure-aks@0.3.0
  gh-cli: circleci/github-cli@2.3.0

workflows:
  Create Release:        
    jobs:
    - gh-cli/release:
        context: aws-dev
        prerelease: false
        notes-file: changelog.md
        tag: 1.0.0 - release 
        title: The initial release
