version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  azure-aks: circleci/azure-aks@0.3.0
  gh-cli: circleci/github-cli@2.3.0


parameters: 
  run-pipeline:
    default: false
    type: boolean

workflows:
  Create Release:
    when: << pipeline.parameters.run-pipeline >>
    jobs:
    # - gh-cli/release:
    #     context: aws-dev
    #     prerelease: false
    #     notes-file: changelog.md
    #     tag: 1.0.0 - release 
    #     title: The initial release
      - create_tag

jobs:
  create_tag:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/repo
    steps:
    - checkout
    - run : 
        name: Choose branch and create tag
        command: |
          if [[ $( git show --oneline | grep "hotfix" ) != ""  ]]; then
            echo "Branch merged from hotfix"
            type=patch
          elif [[ $(git show --oneline | grep "v[0-9].[0-9].[0-9]-release" ) != ""  ]]; then
            echo "Branch merged from release"
            type=minor
          else
            echo "Not merge from release or hotfix"
            type=major
          fi
          new_tag=$(./semantic-versioning.sh $type)
          git push $new_tag 