version: 2.1


workflows:
  Push to Dev:
    jobs:
      push_to_dev:
        machine: 
          image: ubuntu-2004:current
        working_directory: ~/repo
        steps:
          - checkout
          - run:
              command: |
                git checkout origin/dev
                git merge << git.branch >>