apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipes-app
  # Add labels for better organization (optional)
  labels:
    app: recipes
spec:
  project: recipes-suppliers-app # Reference the previously created AppProject
  source:
    # Replace with details for your recipes application Git repository
    repoURL: https://your-git-repo.com/recipes-app.git
    path: helm_charts/apps-chart # Assuming manifests are at the root of the repository
    targetRevision: HEAD # Or specific commit SHA/tag

  # Choose either Helm or Kustomize based on your deployment strategy
  # Uncomment the relevant section and update accordingly

  # Helm deployment (if using Helm chart)
  helm:
    chart: backend-service # Replace with your Helm chart name

  # Sync policy defines automatic synchronization behavior
  syncPolicy:
    syncOptions:
    - CreateNamespace = true
    automated:
      selfHeal: true
      pruneOnDelete: true
