frontend: 
  labels: 
    app: frontend
  deploy: 
    name: frontend-deployment
    replicas: 1
    containers:
      name: 975050257492.dkr.ecr.eu-central-1.amazonaws.com/frontend
      image: frontend
      tag: latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http

  


