frontend: 
  labels: 
    app: frontend
  deploy: 
    name: frontend-deployment
    replicas: 1
    containers:
      name: frontend-app
      image: frontend
      tag: latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http

  


namespace: apps