# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: ebs-sc
# provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer

# ---

# volumeClaimTemplates:
# - metadata:
#     name: data
#   spec:
#     accessModes: ["ReadWriteOnce"]
#     storageClassName: ebs-sc
#     resources:
#       requests:
#         storage: 30Gi

# ---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_DB: dGVzdGRi #testdb
  POSTGRES_USER: dGVzdHVzZXI= #testuser
  POSTGRES_PASSWORD: dGVzdHBhc3M= #testpass 

