# AppProject for recipes and suppliers application

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: recipes-suppliers-app
  description: Application project for recipes and suppliers application
spec:
  # Cluster to target with this project
  destination:
    server: http://kubernetes.default.svc # REPLACE WITH YOUR ARGOCD SERVER URL
    namespace: argocd # REPLACE IF USING A DIFFERENT NAMESPACE

  # Permissions for users to access this project
  roles:
  - groups:
    - developers # REPLACE WITH RELEVANT GROUP FOR ACCESS
    permissions:
    - read
  # Source code location for the application
  source:
    path: helm_charts/apps-chart # REPLACE WITH PATH TO YOUR GIT REPOSITORY
    repoURL: https://github.com/averbuh/UniProject/tree/dev # REPLACE WITH GIT REPOSITORY URL
    targetRevision: HEAD # Adjust if using a specific git tag or commit SHA

  # Sync policy defines how Argo CD will automatically synchronize 
  # application resources with the project's source code
  syncPolicy:
    automated:
      selfHeal: true # Enable automatic healing in case of deployment failures
      pruneOnDelete: true # Prune orphaned resources when source is deleted
