name: CI - PR to Dev
run-name: CI - PR to Dev
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    # Setup Go
    - name: Setup Go 1.22.0 
      uses: actions/setup-go@v5
      with:
        cache: true
        cache-dependency-path: go.sum
        go-version: '1.22.0' # The Go version to download (if necessary) and use.

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    # Run build of the application
    - name: Run build
      working-directory: ./cmd/gin
      run: go build .

    # Run vet & lint on the code
    - name: Run vet & lint
      working-directory: ./cmd/gin
      run: |
        go vet .
        go lint .

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        parallel: [2]
        index: [0, 1]
      fail-fast: false

    steps:
    # Run testing on the code
    - name: Generate go test Slice
      id: test_split
      uses: hashicorp-forge/go-test-split-action@v1
      with:
        total: ${{ matrix.parallel }}
        index: ${{ matrix.index }}

    - name: Run Tests
      working-directory: ./cmd/gin
      run: |
        go test ./... -run "${{ steps.test_split.outputs.run}}"

      # Send slack notification
      #      - name: Send slack notification
      #        uses: 8398a7/action-slack@v3
      #        with:
      #          status: ${{ job.status }}
      #          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #        env:
      #          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #        if: always() # Pick up events even if the job fails or is canceled.
